### ISSUE TITLE
Custom Workflows?

### ISSUE THREAD

**Issue by sebi0920** [Alfresco/alfresco-android-sdk#118]
Hello,
Is it possible to start custom workflows with this sdk?

Greetings
Seb

**Comment by jmpascal** [comment]
Yes it's possible.

Have a look to https://github.com/Alfresco/alfresco-android-sdk/blob/master/tests/alfresco-mobile-android-unit-test-api/src/org/alfresco/mobile/android/test/api/services/WorkflowServiceTest.java

**Comment by sebi0920** [comment]
Thank you for the answer, is it possible to give a sample peace of code, how to work with the test-api?

Best Regards, 
Sebi

**Comment by jmpascal** [comment]
You can have a look to https://github.com/Alfresco/alfresco-android-sdk/wiki/Usage#workflowservice
